apiVersion: apiextensions.crossplane.io/v1alpha1
kind: Composition
metadata:
  name: full.services.clusters.aws.platformref.crossplane.io
  labels:
    plan: full
    provider: helm
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  reclaimPolicy: Delete
  compositeTypeRef:
    apiVersion: clusters.aws.platformref.crossplane.io/v1alpha1
    kind: Services
  resources:
  - base:
      apiVersion: helm.crossplane.io/v1alpha1
      kind: Release
      spec:
        forProvider:
          namespace: operators
          chart:
            # from https://github.com/prometheus-community/helm-charts
            name: prometheus-operator
            repository: https://prometheus-community.github.io/helm-charts
          # Note that default values are overridden by the patches below.
          set:
          - name: image.repository
            value: prom/prometheus
          - name: image.tag
            value: "v2.20.1"
    patches:
    # All Helm releases derive their labels and annotations from the XR.
    - fromFieldPath: metadata.labels
      toFieldPath: metadata.labels
    - fromFieldPath: metadata.annotations
      toFieldPath: metadata.annotations
    # All Helm releases derive the ProviderConfig to use from the XR.
    - fromFieldPath: spec.providerConfigRef.name
      toFieldPath: spec.providerConfigRef.name
    # Derive the Prometheus operator image and tag from the XR.
    - fromFieldPath: spec.operators.prometheus.image
      toFieldPath: spec.forProvider.set[0].value
    - fromFieldPath: spec.operators.prometheus.tag
      toFieldPath: spec.forProvider.set[1].value
