apiVersion: apiextensions.crossplane.io/v1alpha1
kind: CompositeResourceDefinition
metadata:
  name: compositepostgresqlinstances.aws.platformref.crossplane.io
  annotations:
    upbound.io/ui-schema: |-
      ---
      configSections:
      - title: Database Size
        description: Enter information to size your database
        items:
        - name: storageGB
          controlType: singleInput
          type: integer
          path: ".spec.parameters.storageGB"
          title: Storage (GB)
          description: The size in GB for database storage
          default: 10
          validation:
          - minimum: 1
          - maximum: 500
spec:
  claimNames:
    kind: PostgreSQLInstance
    plural: postgresqlinstances
  connectionSecretKeys:
    - username
    - password
    - endpoint
    - port
  crdSpecTemplate:
    group: aws.platformref.crossplane.io
    version: v1alpha1
    names:
      kind: CompositePostgreSQLInstance
      plural: compositepostgresqlinstances
    validation:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  storageGB:
                    type: integer
                  networkRef:
                    type: object
                    description: "A reference to the Network object that this postgres should be
                    connected to."
                    properties:
                      name:
                        type: string
                        description: Name of the Network object this ref points to.
                    required:
                    - name
                required:
                  - storageGB
                  - networkRef
            required:
              - parameters
