apiVersion: apiextensions.crossplane.io/v1alpha1
kind: CompositeResourceDefinition
metadata:
  name: networks.aws.platformref.crossplane.io
spec:
  claimNames:
    kind: Network
    listKind: NetworkList
    plural: networks
    singular: network
  crdSpecTemplate:
    group: aws.platformref.crossplane.io
    version: v1alpha1
    names:
      kind: NetworkGroup
      listKind: NetworkGroupList
      plural: networkgroups
      singular: networkgroup
    validation:
      openAPIV3Schema:
        type: object
        properties:
          spec:
