apiVersion: apiextensions.crossplane.io/v1alpha1
kind: CompositeResourceDefinition
metadata:
  name: compositenetworks.aws.platformref.crossplane.io
  annotations:
    upbound.io/ui-schema: |-
      ---
      configSections:
      - title: Cluster Info
        description: The cluster used with this network fabric
        items:
        - name: clusterRef
          controlType: singleInput
          type: string
          path: ".spec.parameters.clusterRef.name"
          title: Network Ref
          description: Name of the Cluster object this ref points to
          default: cluster
          validation:
          - required: true
            customError: Cluster ref is required.
spec:
  claimNames:
    kind: Network
    plural: networks
  group: aws.platformref.crossplane.io
  names:
    kind: CompositeNetwork
    plural: compositenetworks
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                  description: Name of this Network that other objects will use to refer to it.
                clusterRef:
                  type: object
                  description: "A reference to the Cluster object that this network will be used for."
                  properties:
                    name:
                      type: string
                      description: Name of the Cluster object this ref points to.
                  required:
                    - name
              required:
                - name
                - clusterRef
