apiVersion: apiextensions.crossplane.io/v1alpha1
kind: Composition
metadata:
  name: compositeclusters.aws.platformref.crossplane.io
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  reclaimPolicy: Delete
  compositeTypeRef:
    apiVersion: aws.platformref.crossplane.io/v1alpha1
    kind: CompositeCluster
  resources:
  - base:
      apiVersion: aws.platformref.crossplane.io/v1alpha1
      kind: EKS
    patches:
    - fromFieldPath: metadata.annotations[crossplane.io/external-name]
      toFieldPath: metadata.annotations[crossplane.io/external-name]
    - fromFieldPath: metadata.uid
      toFieldPath: spec.writeConnectionSecretToRef.name
      transforms:
      - type: string
        string:
          fmt: "%s-eks"
    - fromFieldPath: spec.parameters.nodes.count
      toFieldPath: spec.parameters.nodes.count
    - fromFieldPath: spec.parameters.nodes.size
      toFieldPath: spec.parameters.nodes.size
  - base:
      apiVersion: aws.platformref.crossplane.io/v1alpha1
      kind: Services
    patches:
    - fromFieldPath: metadata.uid
      toFieldPath: spec.providerConfigRef.name
      transforms:
      - type: string
        string:
          fmt: "%s-eks"
    - fromFieldPath: spec.parameters.services.operators.prometheus.image
      toFieldPath: spec.operators.prometheus.image
    - fromFieldPath: spec.parameters.services.operators.prometheus.tag
      toFieldPath: spec.operators.prometheus.tag
