apiVersion: apiextensions.crossplane.io/v1alpha1
kind: CompositeResourceDefinition
metadata:
  name: eks.aws.platformref.crossplane.io
spec:
  connectionSecretKeys:
  - kubeconfig
  crdSpecTemplate:
    group: aws.platformref.crossplane.io
    version: v1alpha1
    names:
      kind: EKS
      plural: eks
    validation:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
                description: Name of this Cluster that other objects will use to refer to it.
              parameters:
                type: object
                description: EKS configuration parameters.
                properties:
                  nodes:
                    type: object
                    description: EKS node configuration parameters.
                    properties:
                      count:
                        type: integer
                        description: Desired node count, from 1 to 100.
                      size:
                        type: string
                        description: Size of node.
                        enum:
                        - small
                        - medium
                        - large
                    required:
                    - count
                    - size
                  networkRef:
                    type: object
                    description: "A reference to the Network object that this postgres should be
                    connected to."
                    properties:
                      name:
                        type: string
                        description: Name of the Network object this ref points to.
                    required:
                    - name
                required:
                - nodes
                - networkRef
            required:
            - parameters
